#!/bin/sh

export CMAKE_CLANG_CXX=/usr/bin/clang++
export CMAKE_CLANG_C=/usr/bin/clang

alias ccmake_clang='ccmake -G"Eclipse CDT4 - Unix Makefiles"'
alias ccmake_xcode='ccmake -G"Xcode"'

MECHANICA_DIR=`dirname $0`

echo "dir:${MECHANICA_DIR}"

#    -DOPENMM_BUILD_OPENCL_DOUBLE_PRE=OFF \
#    -DOPENMM_BUILD_OPENCL_TESTS=OFF \

ccmake_xcode \
    -DCMAKE_CXX_COMPILER=${CMAKE_CLANG_CXX} \
    -DCMAKE_C_COMPILER=${CMAKE_CLANG_C} \
    -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_INSTALL_PREFIX=${HOME}/local/openmm \
    -DOPENMM_BUILD_AMOEBA_CUDA_LIB=OFF \
    -DOPENMM_BUILD_CUDA_COMPILER_PLUGIN=OFF \
    -DOPENMM_BUILD_CUDA_LIB=OFF \
    -DOPENMM_BUILD_C_AND_FORTRAN_WRAPPERS=OFF \
    -DOPENMM_BUILD_DRUDE_CUDA_LIB=OFF \
    -DOPENMM_BUILD_DRUDE_OPENCL_LIB=OFF \
    -DOPENMM_BUILD_EXAMPLES=ON \
    -DOPENMM_BUILD_OPENCL_LIB=OFF \
    -DOPENMM_BUILD_PME_PLUGIN=ON \
    -DOPENMM_BUILD_PYTHON_WRAPPERS=OFF \
    -DOPENMM_BUILD_RPMD_CUDA_LIB=OFF \
    -DOPENMM_BUILD_RPMD_OPENCL_LIB=OFF \
    -DOPENMM_BUILD_RPMD_PLUGIN=OFF \
    -DOPENMM_BUILD_RPMD_PLUGIN=OFF \
    -DOPENMM_BUILD_SHARED_LIB=ON \
    -DOPENMM_BUILD_STATIC_LIB=ON \
    -DOPENMM_BUILD_PME_PLUGIN=OFF \
    -DOPENMM_GENERATE_API_DOCS=OFF \
    -DOPENMM_BUILD_AMOEBA_PLUGIN=OFF \
    -DOPENMM_BUILD_DRUDE_PLUGIN=OFF \
    ${MECHANICA_DIR}/deps/openmm
   
   

	     
